services:
  batch:
    image: ghcr.io/phate334/llm-batch:v0.2.1
    user: "${UID:-999}:${GID:-999}"
    volumes:
      - cache:/root/.cache
      - ./data:/app/data
    environment:
      - OPENAI_LOGGER_DATA_DIR=/app/data
      - HTTP_PROXY=http://localhost:8080
    env_file:
      - .env

  llm:
    image: ghcr.io/ggml-org/llama.cpp:server-b7897
    ports:
      - "8080:8080"
    volumes:
      - cache:/root/.cache
    environment:
      - LLAMA_ARG_HF_REPO=lmstudio-community/gemma-3-1B-it-qat-GGUF
      - LLAMA_ARG_N_PARALLEL=2
      - LLAMA_ARG_CTX_SIZE=4096

volumes:
  cache:
