services:
  vllm:
    image: ghcr.io/phate334/vllm:v0.15.1-cpu
    volumes:
      - cache:/root/.cache
    environment:
      - HTTP_PROXY=http://proxy:8080
    env_file:
      - .env
    entrypoint: ""
    command: "tail -f /dev/null"

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    volumes:
      - ./src:/app/src:ro
      - ./data:/app/data
    environment:
      - OPENAI_LOGGER_DATA_DIR=/app/data
    command: [ "mitmdump", "-s", "./src/openai_logger.py" ]

  llm:
    image: ghcr.io/ggml-org/llama.cpp:server-b7897
    ports:
      - "8080:8080"
    volumes:
      - cache:/root/.cache
    environment:
      - LLAMA_ARG_HF_REPO=lmstudio-community/gemma-3-1B-it-qat-GGUF
      - LLAMA_ARG_N_PARALLEL=2
      - LLAMA_ARG_CTX_SIZE=4096

volumes:
  cache:
