services:
  batch:
    image: ghcr.io/phate334/llm-batch:v0.2.2
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    volumes:
      - batch_cache:/home/nonroot/.cache
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
      - HTTP_PROXY=http://localhost:8080
    env_file:
      - .env

  llm:
    image: ghcr.io/ggml-org/llama.cpp:server-b7897
    ports:
      - "8080:8080"
    volumes:
      - llm_cache:/root/.cache
    environment:
      - LLAMA_ARG_HF_REPO=lmstudio-community/gemma-3-1B-it-qat-GGUF
      - LLAMA_ARG_N_PARALLEL=2
      - LLAMA_ARG_CTX_SIZE=4096

volumes:
  batch_cache:
  llm_cache:
